name: Gerar Release Completa

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Dependências
        run: |
          flutter pub get
          python -m pip install --upgrade pip
          pip install pyinstaller cryptography pymysql sqlalchemy fastapi uvicorn

      - name: Build Flutter Windows
        run: flutter build windows --release

      - name: Build Python Server
        # MUDANÇA AQUI: --onefile para gerar um executável independente
        run: pyinstaller --onefile lib/servidor.py

      - name: 📦 ORGANIZAÇÃO FINAL
        shell: cmd
        run: |
          mkdir Pacote_Final
          :: Copia o Flutter
          xcopy /E /I build\windows\x64\runner\Release\* Pacote_Final\
          :: Copia o Servidor (Agora ele está direto na pasta dist\)
          copy dist\servidor.exe Pacote_Final\
          :: Copia a Pasta LIB
          xcopy /E /I lib Pacote_Final\lib\
          :: Copia os extras
          if exist launcher.vbs copy launcher.vbs Pacote_Final\
          if exist .env copy .env Pacote_Final\
          if exist notas.db copy notas.db Pacote_Final\

      - name: 🚀 Upload do Sistema
        uses: actions/upload-artifact@v4
        with:
          name: Sistema-Estoque-Pronto-v2
          path: Pacote_Final/
